CREATE TABLE sekolah (
    sekolah_id UUID PRIMARY KEY,
    nama TEXT NOT NULL,
    nss VARCHAR(20),
    npsn VARCHAR(20),
    bentuk_pendidikan_id INT,
    bentuk_pendidikan_id_str VARCHAR(100),
    status_sekolah VARCHAR(50),
    status_sekolah_str VARCHAR(100),
    alamat_jalan TEXT,
    rt VARCHAR(10),
    rw VARCHAR(10),
    kode_wilayah VARCHAR(20),
    kode_pos VARCHAR(10),
    nomor_telepon VARCHAR(20),
    nomor_fax VARCHAR(20),
    email VARCHAR(100),
    website VARCHAR(100),
    is_sks BOOLEAN DEFAULT FALSE,
    lintang VARCHAR(50),
    bujur VARCHAR(50),
    dusun VARCHAR(100),
    desa_kelurahan VARCHAR(100),
    kecamatan VARCHAR(100),
    kabupaten_kota VARCHAR(100),
    provinsi VARCHAR(100)
);
